name: CI-Node-Build-static-HTML

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v3
     - run: npm install .
     - run: npm install n-readlines fs path
     - run: node build
     - name: Build actions/upload-pages-artifact
       with:
         name: index
         path: |
                ./
                !./**
                !./*.js
                !./*.scroll
                !./*.json
                
       uses: actions/upload-pages-artifact@v1
     - run: node build_profiles
     - name: Build Profies actions/upload-pages-artifact
       with:
         name: pages
         path: |
                ./pages
                !./pages/*.tmp
       uses: actions/upload-pages-artifact@v1 

