name: CI-Node-Build-static-HTML

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
permissions:
  contents: read
  pages: write
  id-token: write
  packages: read 

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  job_1:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: 1 of 2
    runs-on: ubuntu-latest
    # Build job
    steps:
       - name: Checkout
         uses: actions/checkout@v3
       - run: npm install .
       - run: npm install n-readlines fs path
       - run: node build
       - name: Build actions/upload-pages-artifact
         with:
           name: index_html
           path: index.html 
         uses: actions/upload-artifact@v3
       - name: Deploy to GitHub Pages
         uses: actions/deploy-pages@v1
         with:
          artifact_name: index_html
          token: ${{ secrets.GITHUB_TOKEN }}
       - run: node build_profiles
       - name: Build Profies actions/upload-pages-artifact
         with:
           name: profile_htmls
           path: |
                  ./pages
                  !./pages/*.txt
         uses: actions/upload-artifact@v3
  publish-screenshots:
    needs: job_1
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
  job_2:
     needs: job_1
     environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
     name: 2 of 2
     runs-on: ubuntu-latest
     # Build job
     steps:
#       - name: Sleep for 120 seconds
#         run: sleep 30s
        - uses: actions/checkout@v3
        - uses: actions/download-artifact@v3
          with:
            name: pages
        - uses: actions/checkout@v2
        - name: Deploy to GitHub Pages
          id: deployment
          with:
            artifact_name: pages
          uses: actions/deploy-pages@v1
          
            

